FROM ubuntu

RUN apt-get update && apt-get install -y \
    python3.7
    python3-opencv \ 
    mosquitto-clients \
    vim

RUN python -m pip install --upgrade pip
RUN pip install paho-mqtt

RUN mkdir hw3
WORKDIR /hw3
COPY cloud_client.py /hw3/
