FROM alpine:latest
RUN apk update && apk add \
    mosquitto-clients \
    python \
    py-pip

RUN python -m pip install --upgrade pip
RUN python -m pip install paho-mqtt

RUN mkdir /hw3
WORKDIR /hw3

COPY cloud_client.py /hw3/
